export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'Email hoặc mật khẩu không đúng',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  USER_ALREADY_EXISTS: 'Email này đã được đăng ký',
  UNAUTHORIZED: 'Vui lòng đăng nhập để tiếp tục',
  FORBIDDEN: 'Bạn không có quyền thực hiện hành động này',
  INVALID_TOKEN: 'Token không hợp lệ hoặc đã hết hạn',
  TOKEN_REQUIRED: 'Vui lòng cung cấp access token',
  INTERNAL_ERROR: 'Đã xảy ra lỗi, vui lòng thử lại sau',
  VALIDATION_ERROR: 'Dữ liệu không hợp lệ',
  PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm',
  BRAND_NOT_FOUND: 'Không tìm thấy thương hiệu',
  CATEGORY_NOT_FOUND: 'Không tìm thấy danh mục',
  PRODUCT_SLUG_EXISTS: 'Slug sản phẩm đã tồn tại',
  CATEGORY_SLUG_EXISTS: 'Slug danh mục đã tồn tại',
  CATEGORY_NAME_REQUIRED: 'Tên danh mục là bắt buộc',
  CATEGORY_NAME_TOO_SHORT: 'Tên danh mục phải có ít nhất 2 ký tự',
  CATEGORY_NAME_TOO_LONG: 'Tên danh mục không được vượt quá 100 ký tự',
  CATEGORY_PARENT_NOT_FOUND: 'Không tìm thấy danh mục cha',
  CATEGORY_CIRCULAR_REFERENCE: 'Không thể tạo danh mục vòng lặp: danh mục cha không thể là danh mục con của chính nó',
  CATEGORY_CANNOT_BE_OWN_PARENT: 'Danh mục không thể là cha của chính nó',
  CATEGORY_HAS_PRODUCTS: 'Không thể xóa danh mục có sản phẩm đang hoạt động',
  BRAND_SLUG_EXISTS: 'Slug thương hiệu đã tồn tại',
  BRAND_NAME_REQUIRED: 'Tên thương hiệu là bắt buộc',
  BRAND_NAME_TOO_SHORT: 'Tên thương hiệu phải có ít nhất 2 ký tự',
  BRAND_NAME_TOO_LONG: 'Tên thương hiệu không được vượt quá 100 ký tự',
  BRAND_HAS_PRODUCTS: 'Không thể xóa thương hiệu có sản phẩm đang hoạt động',
  REVIEW_NOT_FOUND: 'Không tìm thấy đánh giá',
  REVIEW_ALREADY_EXISTS: 'Bạn đã đánh giá sản phẩm này rồi',
  REVIEW_UNAUTHORIZED: 'Bạn không có quyền chỉnh sửa đánh giá này',
  REVIEW_MUST_PURCHASE: 'Bạn phải mua sản phẩm trước khi đánh giá',
  REVIEW_IMAGE_LIMIT: 'Mỗi đánh giá chỉ được tối đa 5 ảnh',
  REVIEW_IMAGE_NOT_FOUND: 'Không tìm thấy ảnh đánh giá',
  REVIEW_RESPONSE_NOT_FOUND: 'Không tìm thấy phản hồi đánh giá',
  REVIEW_RESPONSE_ALREADY_EXISTS: 'Đánh giá này đã có phản hồi',
  COMMENT_NOT_FOUND: 'Không tìm thấy bình luận',
  COMMENT_UNAUTHORIZED: 'Bạn không có quyền chỉnh sửa bình luận này',
  COMMENT_PARENT_NOT_FOUND: 'Không tìm thấy bình luận cha',
  CART_NOT_FOUND: 'Không tìm thấy giỏ hàng',
  CART_ITEM_NOT_FOUND: 'Không tìm thấy sản phẩm trong giỏ hàng',
  CART_EMPTY: 'Giỏ hàng trống',
  INVALID_QUANTITY: 'Số lượng không hợp lệ',
  VARIANT_NOT_FOUND: 'Không tìm thấy phiên bản sản phẩm',
  VARIANT_OUT_OF_STOCK: 'Sản phẩm không đủ số lượng trong kho',
} as const;

export const SUCCESS_MESSAGES = {
  REGISTRATION_SUCCESS: 'Đăng ký tài khoản thành công',
  LOGIN_SUCCESS: 'Đăng nhập thành công',
  LOGOUT_SUCCESS: 'Đăng xuất thành công',
  TOKEN_REFRESHED: 'Làm mới token thành công',
  GET_CURRENT_USER_SUCCESS: 'Lấy thông tin người dùng thành công',
  UPDATE_USER_SUCCESS: 'Cập nhật thông tin người dùng thành công',
  DELETE_USER_SUCCESS: 'Xóa người dùng thành công',
  GET_PRODUCTS_SUCCESS: 'Lấy danh sách sản phẩm thành công',
  GET_PRODUCT_SUCCESS: 'Lấy thông tin sản phẩm thành công',
  CREATE_PRODUCT_SUCCESS: 'Tạo sản phẩm thành công',
  UPDATE_PRODUCT_SUCCESS: 'Cập nhật sản phẩm thành công',
  DELETE_PRODUCT_SUCCESS: 'Xóa sản phẩm thành công',
  GET_BRANDS_SUCCESS: 'Lấy danh sách thương hiệu thành công',
  GET_BRAND_SUCCESS: 'Lấy thông tin thương hiệu thành công',
  CREATE_BRAND_SUCCESS: 'Tạo thương hiệu thành công',
  UPDATE_BRAND_SUCCESS: 'Cập nhật thương hiệu thành công',
  DELETE_BRAND_SUCCESS: 'Xóa thương hiệu thành công',
  GET_CATEGORIES_SUCCESS: 'Lấy danh sách danh mục thành công',
  GET_CATEGORY_SUCCESS: 'Lấy thông tin danh mục thành công',
  CREATE_CATEGORY_SUCCESS: 'Tạo danh mục thành công',
  UPDATE_CATEGORY_SUCCESS: 'Cập nhật danh mục thành công',
  DELETE_CATEGORY_SUCCESS: 'Xóa danh mục thành công',
  GET_REVIEWS_SUCCESS: 'Lấy danh sách đánh giá thành công',
  GET_REVIEW_SUCCESS: 'Lấy thông tin đánh giá thành công',
  CREATE_REVIEW_SUCCESS: 'Tạo đánh giá thành công',
  UPDATE_REVIEW_SUCCESS: 'Cập nhật đánh giá thành công',
  DELETE_REVIEW_SUCCESS: 'Xóa đánh giá thành công',
  REVIEW_HELPFUL_ADDED: 'Đã đánh dấu hữu ích',
  CREATE_REVIEW_RESPONSE_SUCCESS: 'Tạo phản hồi thành công',
  UPDATE_REVIEW_RESPONSE_SUCCESS: 'Cập nhật phản hồi thành công',
  GET_COMMENTS_SUCCESS: 'Lấy danh sách bình luận thành công',
  GET_COMMENT_SUCCESS: 'Lấy thông tin bình luận thành công',
  CREATE_COMMENT_SUCCESS: 'Tạo bình luận thành công',
  UPDATE_COMMENT_SUCCESS: 'Cập nhật bình luận thành công',
  DELETE_COMMENT_SUCCESS: 'Xóa bình luận thành công',
  GET_CART_SUCCESS: 'Lấy giỏ hàng thành công',
  CART_ITEM_ADDED: 'Đã thêm sản phẩm vào giỏ hàng',
  CART_ITEM_UPDATED: 'Đã cập nhật số lượng sản phẩm',
  CART_ITEM_REMOVED: 'Đã xóa sản phẩm khỏi giỏ hàng',
  CART_CLEARED: 'Đã xóa tất cả sản phẩm trong giỏ hàng',
} as const;

export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export const VALIDATION_RULES = {
  PASSWORD: {
    MIN_LENGTH: 6,
    PATTERN: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/,
  },
  NAME: {
    MIN_LENGTH: 2,
    MAX_LENGTH: 50,
  },
} as const;
